version: 2

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: anytls
builds:
  - id: anytls-client
    binary: anytls-client
    dir: cmd/client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
  - id: anytls-server
    binary: anytls-server
    dir: cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
archives:
  - id: anytls
    ids:
      - anytls-client
      - anytls-server
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip
nfpms:
  - id: anytls
    package_name: anytls
    ids:
      - anytls-client
      - anytls-server
    formats:
      - deb
    maintainer: anytls maintainers
    description: AnyTLS client and server
    license: MIT
    contents:
      - src: examples/anytls-client.service
        dst: /lib/systemd/system/anytls-client.service
      - src: readme.md
        dst: /usr/share/doc/anytls/readme.md
